theme: jekyll-theme-slate
title: Charleston Lean & AI Meetup
description: A community for anyone interested in the intersection of the Lean programming language and artificial intelligence. All levels, from beginners to experts, are welcome.
